default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= AppConfig.database.pool %>
  url: <%= AppConfig.database.url %>
development:
  <<: *default
test:
  <<: *default
  url: <%= AppConfig.database.test_url %>
production:
  <<: *default
